/*
NetFinder for Windows v.1 Copyright (c) 2017 JJ Posti <techtimejourney.net> This program comes with ABSOLUTELY NO WARRANTY; 
for details see: http://www.gnu.org/copyleft/gpl.html. This is free software, and you are welcome to redistribute it under 
GPL Version 2, June 1991")
 */
package netfinder;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;

public class GuiFrame extends javax.swing.JFrame {

    /**
     * Creates new form GuiFrame
     */
    public GuiFrame() {
        initComponents();
                getContentPane().setBackground(java.awt.Color.darkGray); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NetFinder for Windows");
        setMinimumSize(new java.awt.Dimension(213, 100));
        setPreferredSize(new java.awt.Dimension(500, 110));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTextField2.setToolTipText("Search something. Separate words with + (Example:hello+world)");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 244;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(128, 14, 145, 0);
        getContentPane().add(jTextField2, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Google", "Yahoo", "Privatelee", "Wolfram Alpha", "Youtube", "StackoverFlow" }));
        jComboBox1.setToolTipText("Choose search engine.");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(130, 21, 0, 0);
        getContentPane().add(jComboBox1, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        String keywords=jTextField2.getText();
        String searchIn=(jComboBox1.getSelectedItem().toString());
        
        if ("Google" == searchIn){
            String search="https://www.google.com/search?q=";
            String address= search+keywords;
            System.out.println(address);

            Desktop desktop = Desktop.getDesktop();        
            Runtime rt = Runtime.getRuntime();        
            try {
                desktop.browse(URI.create(address));
            } catch (IOException e) {
                System.out.println(e);
            
            }
        
        }
        
        else if ("Yahoo" == searchIn){
            String search="https://us.search.yahoo.com/search;?p=";
        
            String address= search+keywords;
            System.out.println(address);

            Desktop desktop = Desktop.getDesktop();        
            Runtime rt = Runtime.getRuntime();        
            try {
                desktop.browse(URI.create(address));
            } catch (IOException e) {
                System.out.println(e);

            }
        
        }
        
        else if ("Privatelee" == searchIn){
            String search="https://privatelee.com/search/?q=";

            String address= search+keywords;
            System.out.println(address);

            Desktop desktop = Desktop.getDesktop();        
            Runtime rt = Runtime.getRuntime();        
            try {
                desktop.browse(URI.create(address));
            } catch (IOException e) {
                System.out.println(e);

            }
        
        }
        
        else if ("Wolfram Alpha" == searchIn){
            String search="https://www.wolframalpha.com/input/?i=";

            String address= search +keywords;
            System.out.println(address);

            Desktop desktop = Desktop.getDesktop();        
            Runtime rt = Runtime.getRuntime();        
            try {
                desktop.browse(URI.create(address));
            } catch (IOException e) {
                System.out.println(e);

            }
        
        }
                
        else if ("Youtube" == searchIn){
            String search="https://www.youtube.com/results?search_query=";

            String address= search+keywords;
            System.out.println(address);

            Desktop desktop = Desktop.getDesktop();        
            Runtime rt = Runtime.getRuntime();        
            try {
                desktop.browse(URI.create(address));
            } catch (IOException e) {
                System.out.println(e);

            }
            
        }
         
        else if ("StackoverFlow" == searchIn){
            String search="https://stackoverflow.com/search?q=";
             
            String address= search+keywords;
            System.out.println(address);

            Desktop desktop = Desktop.getDesktop();        
            Runtime rt = Runtime.getRuntime();        
            try {
                desktop.browse(URI.create(address));
            } catch (IOException e) {
                System.out.println(e);

            }

        }
               
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int selection=(jComboBox1.getSelectedIndex());
          
        if (0 == selection){
            System.out.println("Google");
        }
        
        else if (1 == selection){
            System.out.println("Yahoo");
        }
        
        else if (2 == selection){
            System.out.println("Privatelee");

        }
        else if (3 == selection){
            System.out.println("Wolfram Alpha");

        }
                        
        else if (4 == selection){
            System.out.println("Youtube");

        }
         
        else if (5 == selection){
            System.out.println("StackoverFlow");

        }
        
        System.out.println(selection);

    }//GEN-LAST:event_jComboBox1ActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
